#!/usr/bin/env python3
"""Native splash assets are generated by generate-book-a-shoot-brand.py."""

from pathlib import Path
import runpy

runpy.run_path(str(Path(__file__).with_name("generate-book-a-shoot-brand.py")), run_name="__main__")
